### ISSUE TITLE
Create Endpoint to Register BST stats logs

### ISSUE THREAD

**Issue by jperata** [bespoken/source-api#107]
This a subtask of to https://github.com/bespoken/bst/issues/462

The objective of this task is to create the endpoint that would receive a JSON object that includes, the following parameters:

    NodeID (optional - since we allow for tests to be run without creating a config)
    Command - utter, intend, speak, launch, proxy, test, e2e)
    Event (optional) - subcategory of command - for proxy it is connect, forward, drop
    For all the other commands, it should just be run for now. We may add other events as we go forward.
    Timestamp

Once received the endpoint should register the data in a new mongo collection created for this stats.

**Comment by ecruzado** [comment]
https://github.com/bespoken/source-api/pull/108
