### ISSUE TITLE
Fix service tests

### ISSUE THREAD

**Issue by ecruzado** [bespoken/source-api#114]
There is a bunch of services tests not running. Some of them are especially critical for us, so they SHOULD be fixed and running. We need to fix them asap. 

The list of tests that were skipped is here:

https://github.com/bespoken/source-api/pull/113/commits/009c8a1d86ba717e2b4f15e051ef25ccbe1c89c4

From there, please fix the following:
- GetSourceId.test.ts 
- GetSources.test.ts 
- GetSourcesByUser.test.ts 
- LinkAVS.test.ts 

And review the following with @jperata to see if they need fixing:
- AddTeamMember.test.ts 
- CreateSourcesFromAmazon.test.ts 
- GetAuthCustomToken.test.ts 
- GetTeam.test.ts 
- v1/PostValidateSource.test.ts 
- v1/SkillTesterParseYaml.test.ts 
- v1/SkillTesterRunYaml.test.ts 
- v1/UpdateNotification.test.ts 

Finally, find if there are more tests being skipped and add them here to decide the next action for them:

**Comment by daisyzarzo** [comment]
according to @jperata  and @AnkRaiza  following tests are not necessary to correct
AddTeamMember.test.ts
GetTeam.test.ts
CreateSourcesFromAmazon.test.ts
v1/PostValidateSource.test.ts
v1/SkillTesterRunYaml.test.ts 
v1/UpdateNotification.test.ts
