### ISSUE TITLE
Add endpoints for management of virtual device tokens following new structure

### ISSUE THREAD

**Issue by jperata** [bespoken/source-api#130]
The virtual devices will follow a new structure, as an array inside the user object from firebase, using a new property called virtualDevices.

Fields of each virtual device would be:
    token (key) - The token_id saved on dynamo
    name - Defaults name are indicated on https://github.com/bespoken/dashboard/issues/733
    creation date 
    platform -  Alexa / Google
    status 

The following endpoints should be created, (endpoints will be created as v2 in order to be able to manage updates on source-api without affecting dashboard)

PUT /v2/virtualDevice
Parameters include:
        userId (from dashboard)
        platform (either alexa or google)
        creation date (from virtual device)

This will create a new virtual device, LinkAVS will be used as base code for this, and won’t save the silentEchoToken anymore but instead store the token as explained.

PATCH  /v2/virtualDevice
Parameters include:
        userId (from dashboard)
        name
        token
        status

Using userId and token as keys a virtual device name or status can be updated.

DELETE  /v2/virtualDevice
Parameters include:
        userId (from dashboard)
        token

To get all the virtual devices from a specific user, the user object can still be used, but the virtual devices needs to be managed by the mentioned endpoints since on each of those there will be interactions with AVS using virtual device.

**Comment by jperata** [comment]
This changes doesn't include changes need for validation to work differently, (part of the reason we are using v2), which have to be addressed on a different issue.

**Comment by jperata** [comment]
The delete virtual device depends on having a new endpoint on virtual device that handles the removal process. The one declared here only will call that endpoint and remove the data on firebase.

**Comment by dmarvp** [comment]
@jperata @AnkRaiza one question about the delete endpoint: are we removing the virtual device from the database or just setting the status to "disabled"? I'd prefer the second option. Otherwise, we wouldn't have any use for the status field.

Also, the endpoint in virtual device is ready for QA: https://github.com/bespoken/virtual-device/issues/191 . Please coordinate with @ecruzado so that you can call it also when removing a virtual device.
