### ISSUE TITLE
Tag users in intercom when removing their accounts from dashboard

### ISSUE THREAD

**Issue by dmarvp** [bespoken/source-api#134]
### Description
When deleting a user from the dashboard (work which was made in #128), use the intercom API to tag the user with the following tag: `deletedFromDashboard`. 

If something fails, this should not stop other steps of the account removal but should be informed in the email that is sent when removing an account fails.

**Comment by MKen-li** [comment]
Move back to dev

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-200
