### ISSUE TITLE
Get users quota

### ISSUE THREAD

**Issue by dmarvp** [bespoken/source-api#174]
## Summary
And endpoint that will return the current quota usage of any given user between two dates.

### endpoint
/v1/quotaUsage

### Parameters
- userId
- startDate
- endDate (optional)

### endpoint logic
The endpoint will:
- In firebase, get the plan the user is subscribed to, in order to get the quota limit for the user
    - Be sure to check if the user has benefits that override the plan quota too
- Get the list of virtual devices associated with the user
- In mongo, query the virtual-device-stats for those virtual devices starting on the **startDate** parameter and up to the **endDate** date.
    - If no **endDate* is supplied, it won't be added to the query.
- From the list of stats do a sum of the **processedMessages**

Response:
```json
{
"userId": "USER_ID",
"plan": "PLAN NAME",
"utterancesQuota": "PLAN or USERS QUOTA",
"utterances": "SUM OF PROCESSED MESSAGES",
"startDate": startDate,
"endDate": endDate
}
```

**Comment by dmarvp** [comment]
@jperata please review when you can. You can do adjustments to the logic or names if needed.

**Comment by dmarvp** [comment]
depends on https://github.com/bespoken/virtual-device/issues/249 to test it, but can be programmed in advance.

**Comment by jperata** [comment]
To test go to:
https://source-api-dev.bespoken.tools/v1/virtualDeviceUsage

This an example of the body:
{
    "userId":"wARoXvMmCIcwEI9WDkS0MFs8pwP2",
    "startDate": "2018-02-18T05:00:00.000Z",
    "endDate": "2019-02-19T05:00:00.000Z"
}

The userId comes from firebase

**Comment by jperata** [comment]
The "utterancesQuota": "PLAN or USERS QUOTA" field would not be added, in both use cases the responsibility for having this value is on the component calling the endpoint, and we want to make this endpoint as fast as possible.

**Comment by MKen-li** [comment]
Marked as verified
Build = aws-dev-95
