### ISSUE TITLE
Users quota by virtual device

### ISSUE THREAD

**Issue by dmarvp** [bespoken/source-api#183]
Related to https://github.com/bespoken/virtual-device/issues/257

### Description
We need an endpoint that will return the user's quota between two dates based on a virtual device id.

The endpoint will:
- Receive a virtual device id and two dates
- Look up the user id that owns that virtual device
- For that user, use the same functionality described here: https://github.com/bespoken/source-api/issues/174

**Comment by ecruzado** [comment]
https://github.com/bespoken/source-api/commit/7ca05374ec237be8215a80ce47ae791b20b46072

**Comment by MKen-li** [comment]
Marked as verified
