### ISSUE TITLE
Add endpoint for receiving token from silent echo

### ISSUE THREAD

**Issue by jkelvie** [bespoken/source-api#20]
Silent Echo, once the user is registered, will make a callback with the token.

The endpoint should be structured like so:
/link_avs

Query String:
user_id: The dashboard user_id for the user
token: The token to be used for interacting with Silent Echo

I've added this issue so the user does not need to cut and paste their ID back into the dashboard

**Comment by chris-ramon** [comment]
closing this one, addressed via: https://github.com/bespoken/source-api/pull/21
