### ISSUE TITLE
Include client in virtual device calls

### ISSUE THREAD

**Issue by dmarvp** [bespoken/source-api#204]
### Description:
related to https://github.com/bespoken/virtual-device-sdk/issues/121
and https://github.com/bespoken/skill-testing-ml/issues/233

Once those issues are implemented, we need to set the parameter "client" to "dashboard" on each call made from this project either by the sdk or the skill-testing-ml libraries.

### Expected behavior
After doing this, the virtual device stats will have a new property in them "client" which will specify "dashboard" in their value.

### Actual behavior
We don't know which client is calling the virtual-device endpoints.

**Comment by daisyzarzo** [comment]
the way to test is doing a validation from dashboard dev
