### ISSUE TITLE
stop silent echo script execution

### ISSUE THREAD

**Issue by chris-ramon** [bespoken/source-api#29]
- `PostValidateSource`:
  - Current implementation does not handle unsubscription from silent-echo-sdk callbacks.
  - Subscribe to the channel being use in dashboard, token + timestamp, and bind to the event:  [channel_vacated](https://pusher.com/docs/webhooks#channel_vacated).
  - Check for `channel_vacated` response, when there are no more subscribers, call `SilentEchoScript.off`, to unsubscribe callbacks.

- `SilentEchoSDK`:
  - Add `SilentEchoScript.off`, which unsubscribe callbacks.
  - Add `SilentEchoScript.constructor` a new param: streaming, default false, which will be used by `execute`. 
  - Update `SilentEchoScript.execute` to check if  `streaming` is true, and no more subscribers, don't call emit, and stop the execution.

- `Dashboard`:
  - Does not require any change for this functionality.

**Comment by dmarvp** [comment]
Won't fix, as we use a new approach now to handle this type of calls.
