### ISSUE TITLE
virtual device sdk syntax errors

### ISSUE THREAD

**Issue by chris-ramon** [bespoken/source-api#48]
- At the moment we show the following error message when there is a syntax error on virtual device side:
  ```
  Sorry, something went wrong we are looking into it.
  ```
- We want to show the correct syntax error coming from virtual device sdk:
  ```
  Invalid script syntax, please provide a script with the following sctructure, each block is a sequence:
  "<Input>": "<ExpectedOutput>"
  "<Input>": "<ExpectedOutput>"
  
  "<Input>": "<ExpectedOutput>"
  ```

**Comment by jkelvie** [comment]
This is a good start. But can we identify where the error is in the script?

**Comment by jperata** [comment]
We removed the open text box for virtual device reducing the original errors and we now manage arrays from the yaml sintax, we also have more detailed failure messages. Closing this one.
