### ISSUE TITLE
login with amazon related changes

### ISSUE THREAD

**Issue by dmarvp** [bespoken/source-api#52]
1. linkAVS.ts
- [x]  open it so that it doesn't need an access_token
- [x]  return a redirect url pointing to the dashboard validation page

2. new endpoint to handle user creation and sign in
- [x] open it so that it doesn't need an access_token
- [x] should receive: email, displayname
- [x] get user by email
- [x] if email does not exist, create a new user in firebase
- [x] create a custom signInToken for the user
- [x] return a the custom firebase auth token
- [x] add/modify tests accordingly

**Comment by dmarvp** [comment]
estimated time 2 days

**Comment by dmarvp** [comment]
In order to test this:
- linkAVS endpoint:
 -- POST https://source-api-dev.bespoken.io/v1/linkAVS
 -- Body {dashboard_user_id, virtual_device_user_id}
- getAuthToken endpoint:
-- POST https://source-api-dev.bespoken.io/v1/authToken
 -- Body {email, virtual_device_user_id, display_name(optional)}

Be sure to check on firebase database that the user has been created.
There's no need to add headers since both endpoints are open.

**Comment by robertonotte** [comment]
@dmarvp is this ticket pending #519 or can it be tested separately?

**Comment by dmarvp** [comment]
@robertonotte this is a backend change in one of our apis, together with other changes on virtual device and dashboard will give you the functionality to login with amazon. Since this is a backend only ticket, @jperata should be the one testing or reviewing it. Maybe we should add a label for backend-only changes?

**Comment by robertonotte** [comment]
@dmarvp I see. Yes, great suggestion, so that I know which ones are under my responsibility.

**Comment by dmarvp** [comment]
Moving back to "Currently implementing" because of changes in the scope. 
Estimated time to completion: half a day.

**Comment by dmarvp** [comment]
Added some more changes to linkAVS endpoint:
- [x] receives and optional smApiAccessToken parameter, if present it saves it into firebase and does not call virtual-device again for a token.
