### ISSUE TITLE
Change Error Messages for Link With Amazon

### ISSUE THREAD

**Issue by jperata** [bespoken/source-api#56]
https://source-api-dev.bespoken.io/v1/linkAVS

Have errors like
<img width="280" alt="screen shot 2018-01-05 at 10 36 47 am" src="https://user-images.githubusercontent.com/8781604/34617104-48102404-f208-11e7-8fb4-25fa32f1c4cc.png">

Which provide no real detail (in this specific case the 404 came from virtual-device not founding the user device id)

Errors generated should be more clear

**Comment by dmarvp** [comment]
Closing because this was already covered in virtual device.
