### ISSUE TITLE
replace env variable VIRTUAL_DEVICE_URL for VIRTUAL_DEVICE_BASE_URL

### ISSUE THREAD

**Issue by dmarvp** [bespoken/source-api#86]
VIRTUAL_DEVICE_BASE_URL is what is used by virtual-device-sdk from the env variables. Right now we have that as VIRTUAL_DEVICE_URL, which means that we are always going to point to the virtual device in prod while working locally. Rename it to VIRTUAL_DEVICE_BASE_URL and change all occurrences to prevent this problem.

Note: right now dev and prod should be working because we are adding an extra env variable to their containers, but the problem should be addressed in code nonetheless.

**Comment by ecruzado** [comment]
https://github.com/bespoken/source-api/pull/123
